name: pdftk
version: '2.02-4'
summary: command-line tool for working with PDF files
description: |
  pdftk is a command-line tool for working with PDF files. It is commonly
  used for client-side scripting or server-side processing of PDF files.

  This snap is an unmodified Ubuntu 16.04 binary package that is
  re-packaged as a snap.

  More info at https://www.pdflabs.com/tools/pdftk-server/ .
grade: stable
confinement: strict

parts:
  archives:
    plugin: nil
    stage-packages:
      - libc6
      - libdb5.3
      - libgcc1
      - libgcj16
      - libstdc++6
      - pdftk
    stage:
      - usr/share/man/man1/pdftk.1.gz
      - usr/bin/pdftk
      - usr/lib/*linux-gnu/*
      - lib/*

apps:
  pdftk:
    command: usr/bin/pdftk
    plugs: [home, removable-media]
